version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"

python:
  install:
  - method: pip
    path: .
    extra_requirements:
    - doc
    - hist

sphinx:
  configuration: doc/conf.py

submodules:
  include: all
