name: Build package / publish

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
    tags: [ "v*" ]
  release:
    types: [ published ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  python-version: "3.13"
  # Uncomment for testing
  # UV_PUBLISH_URL: https://test.pypi.org/legacy/

jobs:
  publish:
    environment:
      name: publish
    permissions:
      id-token: write
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - uses: astral-sh/setup-uv@v5
      with:
        cache-dependency-glob: "**/pyproject.toml"
        python-version: ${{ env.python-version }}
    - run: uv build
    - run: uv publish --trusted-publishing=always
      if: >-
        github.event_name == 'release' || (
          github.event_name == 'push'
          && startsWith(github.ref, 'refs/tags')
        )
